apiVersion: v1
kind: Service
metadata:
  name: atlassian-confluence
  labels:
    name: atlassian-confluence
spec:
  type: NodePort
  selector:
    name: atlassian-confluence
  ports:
    - name: http
      port: 8090
      targetPort: 8090
